# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primaryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class FirstWindow(object):

    def handle_click(self, dialog, new_dialog):
        dialog.hide()
        new_dialog.show()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(15, 10, 460, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.start_test_button = QtWidgets.QPushButton(Dialog)
        self.start_test_button.setGeometry(QtCore.QRect(110, 120, 280, 140))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.start_test_button.setFont(font)
        self.start_test_button.setObjectName("start_test_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate(
            "Dialog", "Find out if you\'re healthy with EngrWeek!!!"))
        self.start_test_button.setText(_translate(
            "Dialog", "Take the BMI test with us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = FirstWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
