# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thirdWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ThirdWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Form")
        Dialog.resize(1049, 717)
        self.bmi_note = QtWidgets.QLabel(Dialog)
        self.bmi_note.setGeometry(QtCore.QRect(570, 130, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bmi_note.setFont(font)
        self.bmi_note.setText("")
        self.bmi_note.setAlignment(QtCore.Qt.AlignCenter)
        self.bmi_note.setOpenExternalLinks(False)
        self.bmi_note.setObjectName("bmi_note")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(520, 40, 20, 641))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(690, 20, 211, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.bmi_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bmi_label.setFont(font)
        self.bmi_label.setText("")
        self.bmi_label.setObjectName("bmi_label")
        self.horizontalLayout.addWidget(self.bmi_label)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(570, 250, 452, 311))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(560, 210, 450, 350))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(560, 570, 450, 51))
        self.label_4.setObjectName("label_4")
        self.exit_button = QtWidgets.QPushButton(Dialog)
        self.exit_button.setGeometry(QtCore.QRect(940, 650, 91, 41))
        self.exit_button.setObjectName("pushButton")
        self.chart_label = QtWidgets.QLabel(Dialog)
        self.chart_label.setGeometry(QtCore.QRect(60, 210, 421, 380))
        self.chart_label.setText("")
        self.chart_label.setObjectName("chart_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate(
            "Form", "Here is an overview of your diet"))
        self.label.setText(_translate("Form", "Your BMI is: "))
        self.label_4.setText(_translate(
            "Form", "On this graph, you can visualise where you fall in weight categories"))
        self.exit_button.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QWidget()
    ui = ThirdWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
